export const BASIL_ICONS = [
  "document-outline",
  "file-outline",
  "folder-outline",
  "book-outline",
  "book-open-outline",
  "bookmark-outline",
  "clipboard-outline",
  "clipboard-alt-outline",
  "note-outline",
  "paper-outline",
  "text-outline",
  "list-outline",
  "grid-outline",
  "columns-outline",
  "rows-outline",
  "layout-outline",
  "dashboard-outline",
  "chart-pie-outline",
  "chart-pie-alt-outline",
  "calendar-outline",
  "clock-outline",
  "alarm-outline",
  "timer-outline",
  "sand-watch-outline",
  "home-outline",
  "apps-outline",
  "menu-outline",
  "search-outline",
  "settings-outline",
  "settings-alt-outline",
  "settings-adjust-outline",
  "user-outline",
  "profile-outline",
  "users-outline",
  "user-plus-outline",
  "user-block-outline",
  "heart-outline",
  "heart-off-outline",
  "star-outline",
  "star-half-outline",
  "award-outline",
  "flag-outline",
  "pin-outline",
  "tag-outline",
  "image-outline",
  "picture-outline",
  "camera-outline",
  "video-outline",
  "music-outline",
  "headphone-outline",
  "microphone-outline",
  "lightbulb-outline",
  "lightbulb-alt-outline",
  "palette-outline",
  "design-outline",
  "code-outline",
  "terminal-outline",
  "server-outline",
  "cloud-outline",
  "cloud-check-outline",
  "database-outline",
  "shield-outline",
  "lock-outline",
  "unlock-outline",
  "key-outline",
  "globe-outline",
  "map-outline",
  "location-outline",
  "world-outline",
  "compass-outline",
  "navigation-outline",
  "envelope-outline",
  "chat-outline",
  "message-outline",
  "comment-outline",
  "phone-outline",
  "notification-outline",
  "bell-outline",
  "gift-outline",
  "bag-outline",
  "wallet-outline",
  "card-outline",
  "shopping-cart-outline",
  "shop-outline",
  "box-outline",
  "layers-outline",
  "stack-outline",
  "diamond-outline",
  "fire-outline",
  "thunder-outline",
  "sun-outline",
  "moon-outline",
  "umbrella-outline",
  "drop-outline",
  "coffee-outline",
  "medkit-outline",
  "binocular-outline",
  "cursor-outline",
  "move-outline",
  "exchange-outline",
  "share-outline",
  "link-outline",
  "attach-outline",
  "download-outline",
  "upload-outline",
  "save-outline",
  "printer-outline",
  "monitor-outline",
  "desktop-outline",
  "mobile-phone-outline",
  "gamepad-outline",
  "headset-outline",
  "watch-outline",
];

export const PAGE_ICONS = [
  "document-outline",
  "file-outline",
  "clipboard-outline",
  "clipboard-alt-outline",
  "book-outline",
  "book-open-outline",
  "bookmark-outline",
  "edit-outline",
  "edit-alt-outline",
  "columns-outline",
  "rows-outline",
  "layout-outline",
  "chart-pie-outline",
  "chart-pie-alt-outline",
  "calendar-outline",
  "clock-outline",
  "alarm-outline",
  "timer-outline",
  "home-outline",
  "star-outline",
  "heart-outline",
  "bookmark-outline",
  "pin-outline",
  "image-outline",
  "picture-outline",
  "camera-outline",
  "video-outline",
  "music-outline",
  "microphone-outline",
  "lightbulb-outline",
  "lightbulb-alt-outline",
  "palette-outline",
  "settings-outline",
  "user-outline",
  "globe-outline",
  "map-location-outline",
  "location-outline",
  "chat-outline",
  "envelope-outline",
  "phone-outline",
  "bag-outline",
  "wallet-outline",
  "card-outline",
  "shopping-cart-outline",
  "diamond-outline",
  "fire-outline",
  "lightning-outline",
  "sun-outline",
  "moon-outline",
  "gamepad-outline",
  "headset-outline",
];

export const WORKSPACE_ICONS = [
  "folder-outline",
  "folder-open-outline",
  "folder-plus-outline",
  "folder-block-outline",
  "folder-lock-outline",
  "folder-user-outline",
  "home-outline",
  "apps-outline",
  "layout-outline",
  "columns-outline",
  "star-outline",
  "bag-outline",
  "lightbulb-outline",
  "globe-outline",
  "server-outline",
  "cloud-outline",
];

function isEmoji(s: string): boolean {
  const code = s.codePointAt(0);
  if (!code) return false;
  return (
    code >= 0x1f000 ||
    code === 0x2605 ||
    code === 0x2606 ||
    code === 0x2b50 ||
    code === 0x2764
  );
}

export function getIconClass(icon: string | null | undefined): string {
  if (!icon) return "basil:document-outline";
  if (isEmoji(icon)) return icon;
  return `basil:${icon}`;
}
